name: Main on push
on:
  push:
    branches:
      main
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: testing
        run: go test -v ./...